/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MeterReadingType } from './MeterReadingType';
import {
    MeterReadingTypeFromJSON,
    MeterReadingTypeFromJSONTyped,
    MeterReadingTypeToJSON,
    MeterReadingTypeToJSONTyped,
} from './MeterReadingType';

/**
 * 
 * @export
 * @interface AppReportMeterReading
 */
export interface AppReportMeterReading {
    /**
     * 
     * @type {number}
     * @memberof AppReportMeterReading
     */
    value?: number;
    /**
     * 
     * @type {MeterReadingType}
     * @memberof AppReportMeterReading
     */
    type?: MeterReadingType;
}



/**
 * Check if a given object implements the AppReportMeterReading interface.
 */
export function instanceOfAppReportMeterReading(value: object): value is AppReportMeterReading {
    return true;
}

export function AppReportMeterReadingFromJSON(json: any): AppReportMeterReading {
    return AppReportMeterReadingFromJSONTyped(json, false);
}

export function AppReportMeterReadingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportMeterReading {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['Value'] == null ? undefined : json['Value'],
        'type': json['Type'] == null ? undefined : MeterReadingTypeFromJSON(json['Type']),
    };
}

export function AppReportMeterReadingToJSON(json: any): AppReportMeterReading {
    return AppReportMeterReadingToJSONTyped(json, false);
}

export function AppReportMeterReadingToJSONTyped(value?: AppReportMeterReading | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Value': value['value'],
        'Type': MeterReadingTypeToJSON(value['type']),
    };
}

