/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppReportMeterReading } from './AppReportMeterReading';
import {
    AppReportMeterReadingFromJSON,
    AppReportMeterReadingFromJSONTyped,
    AppReportMeterReadingToJSON,
    AppReportMeterReadingToJSONTyped,
} from './AppReportMeterReading';
import type { AppReportValue } from './AppReportValue';
import {
    AppReportValueFromJSON,
    AppReportValueFromJSONTyped,
    AppReportValueToJSON,
    AppReportValueToJSONTyped,
} from './AppReportValue';

/**
 * 
 * @export
 * @interface AppReportSummaryHeat
 */
export interface AppReportSummaryHeat {
    /**
     * 
     * @type {Array<AppReportMeterReading>}
     * @memberof AppReportSummaryHeat
     */
    meterReadings?: Array<AppReportMeterReading> | null;
    /**
     * 
     * @type {Array<AppReportValue>}
     * @memberof AppReportSummaryHeat
     */
    reportValues?: Array<AppReportValue> | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryHeat
     */
    sumCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryHeat
     */
    sumCubicMeter?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryHeat
     */
    maxCubicMeter?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryHeat
     */
    sumKiloWattHour?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryHeat
     */
    maxKiloWattHour?: number;
}

/**
 * Check if a given object implements the AppReportSummaryHeat interface.
 */
export function instanceOfAppReportSummaryHeat(value: object): value is AppReportSummaryHeat {
    return true;
}

export function AppReportSummaryHeatFromJSON(json: any): AppReportSummaryHeat {
    return AppReportSummaryHeatFromJSONTyped(json, false);
}

export function AppReportSummaryHeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportSummaryHeat {
    if (json == null) {
        return json;
    }
    return {
        
        'meterReadings': json['MeterReadings'] == null ? undefined : ((json['MeterReadings'] as Array<any>).map(AppReportMeterReadingFromJSON)),
        'reportValues': json['ReportValues'] == null ? undefined : ((json['ReportValues'] as Array<any>).map(AppReportValueFromJSON)),
        'sumCurrency': json['SumCurrency'] == null ? undefined : json['SumCurrency'],
        'sumCubicMeter': json['SumCubicMeter'] == null ? undefined : json['SumCubicMeter'],
        'maxCubicMeter': json['MaxCubicMeter'] == null ? undefined : json['MaxCubicMeter'],
        'sumKiloWattHour': json['SumKiloWattHour'] == null ? undefined : json['SumKiloWattHour'],
        'maxKiloWattHour': json['MaxKiloWattHour'] == null ? undefined : json['MaxKiloWattHour'],
    };
}

export function AppReportSummaryHeatToJSON(json: any): AppReportSummaryHeat {
    return AppReportSummaryHeatToJSONTyped(json, false);
}

export function AppReportSummaryHeatToJSONTyped(value?: AppReportSummaryHeat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MeterReadings': value['meterReadings'] == null ? undefined : ((value['meterReadings'] as Array<any>).map(AppReportMeterReadingToJSON)),
        'ReportValues': value['reportValues'] == null ? undefined : ((value['reportValues'] as Array<any>).map(AppReportValueToJSON)),
        'SumCurrency': value['sumCurrency'],
        'SumCubicMeter': value['sumCubicMeter'],
        'MaxCubicMeter': value['maxCubicMeter'],
        'SumKiloWattHour': value['sumKiloWattHour'],
        'MaxKiloWattHour': value['maxKiloWattHour'],
    };
}

