/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppReportMeterReading } from './AppReportMeterReading';
import {
    AppReportMeterReadingFromJSON,
    AppReportMeterReadingFromJSONTyped,
    AppReportMeterReadingToJSON,
    AppReportMeterReadingToJSONTyped,
} from './AppReportMeterReading';
import type { AppReportValue } from './AppReportValue';
import {
    AppReportValueFromJSON,
    AppReportValueFromJSONTyped,
    AppReportValueToJSON,
    AppReportValueToJSONTyped,
} from './AppReportValue';

/**
 * 
 * @export
 * @interface AppReportSummaryWater
 */
export interface AppReportSummaryWater {
    /**
     * 
     * @type {Array<AppReportMeterReading>}
     * @memberof AppReportSummaryWater
     */
    meterReadings?: Array<AppReportMeterReading> | null;
    /**
     * 
     * @type {Array<AppReportValue>}
     * @memberof AppReportSummaryWater
     */
    reportValues?: Array<AppReportValue> | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    sumCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    sumCurrencyCold?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    sumCubicMeterCold?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    maxCubicMeterCold?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    sumCurrencyWarm?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    sumCubicMeterWarm?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryWater
     */
    maxCubicMeterWarm?: number;
}

/**
 * Check if a given object implements the AppReportSummaryWater interface.
 */
export function instanceOfAppReportSummaryWater(value: object): value is AppReportSummaryWater {
    return true;
}

export function AppReportSummaryWaterFromJSON(json: any): AppReportSummaryWater {
    return AppReportSummaryWaterFromJSONTyped(json, false);
}

export function AppReportSummaryWaterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportSummaryWater {
    if (json == null) {
        return json;
    }
    return {
        
        'meterReadings': json['MeterReadings'] == null ? undefined : ((json['MeterReadings'] as Array<any>).map(AppReportMeterReadingFromJSON)),
        'reportValues': json['ReportValues'] == null ? undefined : ((json['ReportValues'] as Array<any>).map(AppReportValueFromJSON)),
        'sumCurrency': json['SumCurrency'] == null ? undefined : json['SumCurrency'],
        'sumCurrencyCold': json['SumCurrencyCold'] == null ? undefined : json['SumCurrencyCold'],
        'sumCubicMeterCold': json['SumCubicMeterCold'] == null ? undefined : json['SumCubicMeterCold'],
        'maxCubicMeterCold': json['MaxCubicMeterCold'] == null ? undefined : json['MaxCubicMeterCold'],
        'sumCurrencyWarm': json['SumCurrencyWarm'] == null ? undefined : json['SumCurrencyWarm'],
        'sumCubicMeterWarm': json['SumCubicMeterWarm'] == null ? undefined : json['SumCubicMeterWarm'],
        'maxCubicMeterWarm': json['MaxCubicMeterWarm'] == null ? undefined : json['MaxCubicMeterWarm'],
    };
}

export function AppReportSummaryWaterToJSON(json: any): AppReportSummaryWater {
    return AppReportSummaryWaterToJSONTyped(json, false);
}

export function AppReportSummaryWaterToJSONTyped(value?: AppReportSummaryWater | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MeterReadings': value['meterReadings'] == null ? undefined : ((value['meterReadings'] as Array<any>).map(AppReportMeterReadingToJSON)),
        'ReportValues': value['reportValues'] == null ? undefined : ((value['reportValues'] as Array<any>).map(AppReportValueToJSON)),
        'SumCurrency': value['sumCurrency'],
        'SumCurrencyCold': value['sumCurrencyCold'],
        'SumCubicMeterCold': value['sumCubicMeterCold'],
        'MaxCubicMeterCold': value['maxCubicMeterCold'],
        'SumCurrencyWarm': value['sumCurrencyWarm'],
        'SumCubicMeterWarm': value['sumCubicMeterWarm'],
        'MaxCubicMeterWarm': value['maxCubicMeterWarm'],
    };
}

