/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppReportMeterReading } from './AppReportMeterReading';
import {
    AppReportMeterReadingFromJSON,
    AppReportMeterReadingFromJSONTyped,
    AppReportMeterReadingToJSON,
    AppReportMeterReadingToJSONTyped,
} from './AppReportMeterReading';
import type { AppReportValue } from './AppReportValue';
import {
    AppReportValueFromJSON,
    AppReportValueFromJSONTyped,
    AppReportValueToJSON,
    AppReportValueToJSONTyped,
} from './AppReportValue';

/**
 * 
 * @export
 * @interface AppReportSummaryPower
 */
export interface AppReportSummaryPower {
    /**
     * 
     * @type {Array<AppReportMeterReading>}
     * @memberof AppReportSummaryPower
     */
    meterReadings?: Array<AppReportMeterReading> | null;
    /**
     * 
     * @type {Array<AppReportValue>}
     * @memberof AppReportSummaryPower
     */
    reportValues?: Array<AppReportValue> | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    sumCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    startTimeCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    sum?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    max?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryPower
     */
    maxCurrency?: number;
}

/**
 * Check if a given object implements the AppReportSummaryPower interface.
 */
export function instanceOfAppReportSummaryPower(value: object): value is AppReportSummaryPower {
    return true;
}

export function AppReportSummaryPowerFromJSON(json: any): AppReportSummaryPower {
    return AppReportSummaryPowerFromJSONTyped(json, false);
}

export function AppReportSummaryPowerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportSummaryPower {
    if (json == null) {
        return json;
    }
    return {
        
        'meterReadings': json['MeterReadings'] == null ? undefined : ((json['MeterReadings'] as Array<any>).map(AppReportMeterReadingFromJSON)),
        'reportValues': json['ReportValues'] == null ? undefined : ((json['ReportValues'] as Array<any>).map(AppReportValueFromJSON)),
        'sumCurrency': json['SumCurrency'] == null ? undefined : json['SumCurrency'],
        'startTime': json['StartTime'] == null ? undefined : json['StartTime'],
        'startTimeCurrency': json['StartTimeCurrency'] == null ? undefined : json['StartTimeCurrency'],
        'sum': json['Sum'] == null ? undefined : json['Sum'],
        'max': json['Max'] == null ? undefined : json['Max'],
        'maxCurrency': json['MaxCurrency'] == null ? undefined : json['MaxCurrency'],
    };
}

export function AppReportSummaryPowerToJSON(json: any): AppReportSummaryPower {
    return AppReportSummaryPowerToJSONTyped(json, false);
}

export function AppReportSummaryPowerToJSONTyped(value?: AppReportSummaryPower | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MeterReadings': value['meterReadings'] == null ? undefined : ((value['meterReadings'] as Array<any>).map(AppReportMeterReadingToJSON)),
        'ReportValues': value['reportValues'] == null ? undefined : ((value['reportValues'] as Array<any>).map(AppReportValueToJSON)),
        'SumCurrency': value['sumCurrency'],
        'StartTime': value['startTime'],
        'StartTimeCurrency': value['startTimeCurrency'],
        'Sum': value['sum'],
        'Max': value['max'],
        'MaxCurrency': value['maxCurrency'],
    };
}

