/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppReportMeterReading } from './AppReportMeterReading';
import {
    AppReportMeterReadingFromJSON,
    AppReportMeterReadingFromJSONTyped,
    AppReportMeterReadingToJSON,
    AppReportMeterReadingToJSONTyped,
} from './AppReportMeterReading';
import type { AppReportValue } from './AppReportValue';
import {
    AppReportValueFromJSON,
    AppReportValueFromJSONTyped,
    AppReportValueToJSON,
    AppReportValueToJSONTyped,
} from './AppReportValue';

/**
 * 
 * @export
 * @interface AppReportSummaryGas
 */
export interface AppReportSummaryGas {
    /**
     * 
     * @type {Array<AppReportMeterReading>}
     * @memberof AppReportSummaryGas
     */
    meterReadings?: Array<AppReportMeterReading> | null;
    /**
     * 
     * @type {Array<AppReportValue>}
     * @memberof AppReportSummaryGas
     */
    reportValues?: Array<AppReportValue> | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    sumCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    totalDelta?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    sum?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    totalDeltaCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    currentConsumptionKwh?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    currentConsumption?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    consumptionKWh?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    consumption?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    max?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    maxCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    maxConsumption?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    maxConsumptionKWh?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    minConsumption?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    minConsumptionKWh?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    avgDelta?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    avgConsumption?: number;
    /**
     * 
     * @type {number}
     * @memberof AppReportSummaryGas
     */
    avgConsumptionKWh?: number;
}

/**
 * Check if a given object implements the AppReportSummaryGas interface.
 */
export function instanceOfAppReportSummaryGas(value: object): value is AppReportSummaryGas {
    return true;
}

export function AppReportSummaryGasFromJSON(json: any): AppReportSummaryGas {
    return AppReportSummaryGasFromJSONTyped(json, false);
}

export function AppReportSummaryGasFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportSummaryGas {
    if (json == null) {
        return json;
    }
    return {
        
        'meterReadings': json['MeterReadings'] == null ? undefined : ((json['MeterReadings'] as Array<any>).map(AppReportMeterReadingFromJSON)),
        'reportValues': json['ReportValues'] == null ? undefined : ((json['ReportValues'] as Array<any>).map(AppReportValueFromJSON)),
        'sumCurrency': json['SumCurrency'] == null ? undefined : json['SumCurrency'],
        'totalDelta': json['TotalDelta'] == null ? undefined : json['TotalDelta'],
        'sum': json['Sum'] == null ? undefined : json['Sum'],
        'totalDeltaCurrency': json['TotalDeltaCurrency'] == null ? undefined : json['TotalDeltaCurrency'],
        'currentConsumptionKwh': json['CurrentConsumptionKwh'] == null ? undefined : json['CurrentConsumptionKwh'],
        'currentConsumption': json['CurrentConsumption'] == null ? undefined : json['CurrentConsumption'],
        'consumptionKWh': json['ConsumptionKWh'] == null ? undefined : json['ConsumptionKWh'],
        'consumption': json['Consumption'] == null ? undefined : json['Consumption'],
        'max': json['Max'] == null ? undefined : json['Max'],
        'maxCurrency': json['MaxCurrency'] == null ? undefined : json['MaxCurrency'],
        'maxConsumption': json['MaxConsumption'] == null ? undefined : json['MaxConsumption'],
        'maxConsumptionKWh': json['MaxConsumptionKWh'] == null ? undefined : json['MaxConsumptionKWh'],
        'min': json['Min'] == null ? undefined : json['Min'],
        'minConsumption': json['MinConsumption'] == null ? undefined : json['MinConsumption'],
        'minConsumptionKWh': json['MinConsumptionKWh'] == null ? undefined : json['MinConsumptionKWh'],
        'avgDelta': json['AvgDelta'] == null ? undefined : json['AvgDelta'],
        'avgConsumption': json['AvgConsumption'] == null ? undefined : json['AvgConsumption'],
        'avgConsumptionKWh': json['AvgConsumptionKWh'] == null ? undefined : json['AvgConsumptionKWh'],
    };
}

export function AppReportSummaryGasToJSON(json: any): AppReportSummaryGas {
    return AppReportSummaryGasToJSONTyped(json, false);
}

export function AppReportSummaryGasToJSONTyped(value?: AppReportSummaryGas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MeterReadings': value['meterReadings'] == null ? undefined : ((value['meterReadings'] as Array<any>).map(AppReportMeterReadingToJSON)),
        'ReportValues': value['reportValues'] == null ? undefined : ((value['reportValues'] as Array<any>).map(AppReportValueToJSON)),
        'SumCurrency': value['sumCurrency'],
        'TotalDelta': value['totalDelta'],
        'Sum': value['sum'],
        'TotalDeltaCurrency': value['totalDeltaCurrency'],
        'CurrentConsumptionKwh': value['currentConsumptionKwh'],
        'CurrentConsumption': value['currentConsumption'],
        'ConsumptionKWh': value['consumptionKWh'],
        'Consumption': value['consumption'],
        'Max': value['max'],
        'MaxCurrency': value['maxCurrency'],
        'MaxConsumption': value['maxConsumption'],
        'MaxConsumptionKWh': value['maxConsumptionKWh'],
        'Min': value['min'],
        'MinConsumption': value['minConsumption'],
        'MinConsumptionKWh': value['minConsumptionKWh'],
        'AvgDelta': value['avgDelta'],
        'AvgConsumption': value['avgConsumption'],
        'AvgConsumptionKWh': value['avgConsumptionKWh'],
    };
}

