/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValuesType } from './ValuesType';
import {
    ValuesTypeFromJSON,
    ValuesTypeFromJSONTyped,
    ValuesTypeToJSON,
    ValuesTypeToJSONTyped,
} from './ValuesType';

/**
 * 
 * @export
 * @interface AppReportValue
 */
export interface AppReportValue {
    /**
     * 
     * @type {string}
     * @memberof AppReportValue
     */
    deviceId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    timestamp?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AppReportValue
     */
    complete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    delta?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    totalDelta?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    totalDeltaCurrency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaHT?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaNT?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCurrency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    consumption?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    consumptionKWh?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    amountOfValuesAdded?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaKiloWattHour?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCubicMeter?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCubicMeterCold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCubicMeterWarm?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCurrencyCold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    deltaCurrencyWarm?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    currentConsumption?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AppReportValue
     */
    currentConsumptionKwh?: number | null;
    /**
     * 
     * @type {ValuesType}
     * @memberof AppReportValue
     */
    valuesType?: ValuesType;
}



/**
 * Check if a given object implements the AppReportValue interface.
 */
export function instanceOfAppReportValue(value: object): value is AppReportValue {
    return true;
}

export function AppReportValueFromJSON(json: any): AppReportValue {
    return AppReportValueFromJSONTyped(json, false);
}

export function AppReportValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppReportValue {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['DeviceId'] == null ? undefined : json['DeviceId'],
        'timestamp': json['Timestamp'] == null ? undefined : json['Timestamp'],
        'complete': json['Complete'] == null ? undefined : json['Complete'],
        'delta': json['Delta'] == null ? undefined : json['Delta'],
        'totalDelta': json['TotalDelta'] == null ? undefined : json['TotalDelta'],
        'totalDeltaCurrency': json['TotalDeltaCurrency'] == null ? undefined : json['TotalDeltaCurrency'],
        'deltaHT': json['DeltaHT'] == null ? undefined : json['DeltaHT'],
        'deltaNT': json['DeltaNT'] == null ? undefined : json['DeltaNT'],
        'deltaCurrency': json['DeltaCurrency'] == null ? undefined : json['DeltaCurrency'],
        'consumption': json['Consumption'] == null ? undefined : json['Consumption'],
        'consumptionKWh': json['ConsumptionKWh'] == null ? undefined : json['ConsumptionKWh'],
        'amountOfValuesAdded': json['AmountOfValuesAdded'] == null ? undefined : json['AmountOfValuesAdded'],
        'deltaKiloWattHour': json['DeltaKiloWattHour'] == null ? undefined : json['DeltaKiloWattHour'],
        'deltaCubicMeter': json['DeltaCubicMeter'] == null ? undefined : json['DeltaCubicMeter'],
        'deltaCubicMeterCold': json['DeltaCubicMeterCold'] == null ? undefined : json['DeltaCubicMeterCold'],
        'deltaCubicMeterWarm': json['DeltaCubicMeterWarm'] == null ? undefined : json['DeltaCubicMeterWarm'],
        'deltaCurrencyCold': json['DeltaCurrencyCold'] == null ? undefined : json['DeltaCurrencyCold'],
        'deltaCurrencyWarm': json['DeltaCurrencyWarm'] == null ? undefined : json['DeltaCurrencyWarm'],
        'currentConsumption': json['CurrentConsumption'] == null ? undefined : json['CurrentConsumption'],
        'currentConsumptionKwh': json['CurrentConsumptionKwh'] == null ? undefined : json['CurrentConsumptionKwh'],
        'valuesType': json['ValuesType'] == null ? undefined : ValuesTypeFromJSON(json['ValuesType']),
    };
}

export function AppReportValueToJSON(json: any): AppReportValue {
    return AppReportValueToJSONTyped(json, false);
}

export function AppReportValueToJSONTyped(value?: AppReportValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'DeviceId': value['deviceId'],
        'Timestamp': value['timestamp'],
        'Complete': value['complete'],
        'Delta': value['delta'],
        'TotalDelta': value['totalDelta'],
        'TotalDeltaCurrency': value['totalDeltaCurrency'],
        'DeltaHT': value['deltaHT'],
        'DeltaNT': value['deltaNT'],
        'DeltaCurrency': value['deltaCurrency'],
        'Consumption': value['consumption'],
        'ConsumptionKWh': value['consumptionKWh'],
        'AmountOfValuesAdded': value['amountOfValuesAdded'],
        'DeltaKiloWattHour': value['deltaKiloWattHour'],
        'DeltaCubicMeter': value['deltaCubicMeter'],
        'DeltaCubicMeterCold': value['deltaCubicMeterCold'],
        'DeltaCubicMeterWarm': value['deltaCubicMeterWarm'],
        'DeltaCurrencyCold': value['deltaCurrencyCold'],
        'DeltaCurrencyWarm': value['deltaCurrencyWarm'],
        'CurrentConsumption': value['currentConsumption'],
        'CurrentConsumptionKwh': value['currentConsumptionKwh'],
        'ValuesType': ValuesTypeToJSON(value['valuesType']),
    };
}

