/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Divisions = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_MINUS_1: -1
} as const;
export type Divisions = typeof Divisions[keyof typeof Divisions];


export function instanceOfDivisions(value: any): boolean {
    for (const key in Divisions) {
        if (Object.prototype.hasOwnProperty.call(Divisions, key)) {
            if (Divisions[key as keyof typeof Divisions] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DivisionsFromJSON(json: any): Divisions {
    return DivisionsFromJSONTyped(json, false);
}

export function DivisionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Divisions {
    return json as Divisions;
}

export function DivisionsToJSON(value?: Divisions | null): any {
    return value as any;
}

export function DivisionsToJSONTyped(value: any, ignoreDiscriminator: boolean): Divisions {
    return value as Divisions;
}

