/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MeterReadingType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_101: 101,
    NUMBER_202: 202,
    NUMBER_301: 301,
    NUMBER_302: 302,
    NUMBER_401: 401
} as const;
export type MeterReadingType = typeof MeterReadingType[keyof typeof MeterReadingType];


export function instanceOfMeterReadingType(value: any): boolean {
    for (const key in MeterReadingType) {
        if (Object.prototype.hasOwnProperty.call(MeterReadingType, key)) {
            if (MeterReadingType[key as keyof typeof MeterReadingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MeterReadingTypeFromJSON(json: any): MeterReadingType {
    return MeterReadingTypeFromJSONTyped(json, false);
}

export function MeterReadingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeterReadingType {
    return json as MeterReadingType;
}

export function MeterReadingTypeToJSON(value?: MeterReadingType | null): any {
    return value as any;
}

export function MeterReadingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MeterReadingType {
    return value as MeterReadingType;
}

