/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyCurrentDataModel
 */
export interface MyCurrentDataModel {
    /**
     * 
     * @type {string}
     * @memberof MyCurrentDataModel
     */
    deviceId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MyCurrentDataModel
     */
    outdated?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    watt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    kiloWattHour?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    deltaKiloWattHour?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    cubicMeterCold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    cubicMeterWarm?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    cubicMeter?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    deltaCubicMeter?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    aPlus?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    aPlusHT?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    aPlusNT?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    aMinus?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    l1?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    l2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MyCurrentDataModel
     */
    l3?: number | null;
}

/**
 * Check if a given object implements the MyCurrentDataModel interface.
 */
export function instanceOfMyCurrentDataModel(value: object): value is MyCurrentDataModel {
    return true;
}

export function MyCurrentDataModelFromJSON(json: any): MyCurrentDataModel {
    return MyCurrentDataModelFromJSONTyped(json, false);
}

export function MyCurrentDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyCurrentDataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['DeviceId'] == null ? undefined : json['DeviceId'],
        'outdated': json['Outdated'] == null ? undefined : json['Outdated'],
        'watt': json['Watt'] == null ? undefined : json['Watt'],
        'kiloWattHour': json['KiloWattHour'] == null ? undefined : json['KiloWattHour'],
        'deltaKiloWattHour': json['DeltaKiloWattHour'] == null ? undefined : json['DeltaKiloWattHour'],
        'cubicMeterCold': json['CubicMeterCold'] == null ? undefined : json['CubicMeterCold'],
        'cubicMeterWarm': json['CubicMeterWarm'] == null ? undefined : json['CubicMeterWarm'],
        'cubicMeter': json['CubicMeter'] == null ? undefined : json['CubicMeter'],
        'deltaCubicMeter': json['DeltaCubicMeter'] == null ? undefined : json['DeltaCubicMeter'],
        'timestamp': json['Timestamp'] == null ? undefined : json['Timestamp'],
        'aPlus': json['A_Plus'] == null ? undefined : json['A_Plus'],
        'aPlusHT': json['A_Plus_HT'] == null ? undefined : json['A_Plus_HT'],
        'aPlusNT': json['A_Plus_NT'] == null ? undefined : json['A_Plus_NT'],
        'aMinus': json['A_Minus'] == null ? undefined : json['A_Minus'],
        'l1': json['L1'] == null ? undefined : json['L1'],
        'l2': json['L2'] == null ? undefined : json['L2'],
        'l3': json['L3'] == null ? undefined : json['L3'],
    };
}

export function MyCurrentDataModelToJSON(json: any): MyCurrentDataModel {
    return MyCurrentDataModelToJSONTyped(json, false);
}

export function MyCurrentDataModelToJSONTyped(value?: MyCurrentDataModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'DeviceId': value['deviceId'],
        'Outdated': value['outdated'],
        'Watt': value['watt'],
        'KiloWattHour': value['kiloWattHour'],
        'DeltaKiloWattHour': value['deltaKiloWattHour'],
        'CubicMeterCold': value['cubicMeterCold'],
        'CubicMeterWarm': value['cubicMeterWarm'],
        'CubicMeter': value['cubicMeter'],
        'DeltaCubicMeter': value['deltaCubicMeter'],
        'Timestamp': value['timestamp'],
        'A_Plus': value['aPlus'],
        'A_Plus_HT': value['aPlusHT'],
        'A_Plus_NT': value['aPlusNT'],
        'A_Minus': value['aMinus'],
        'L1': value['l1'],
        'L2': value['l2'],
        'L3': value['l3'],
    };
}

