/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperatingReportValueModel
 */
export interface OperatingReportValueModel {
    /**
     * 
     * @type {number}
     * @memberof OperatingReportValueModel
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof OperatingReportValueModel
     */
    value?: number | null;
}

/**
 * Check if a given object implements the OperatingReportValueModel interface.
 */
export function instanceOfOperatingReportValueModel(value: object): value is OperatingReportValueModel {
    return true;
}

export function OperatingReportValueModelFromJSON(json: any): OperatingReportValueModel {
    return OperatingReportValueModelFromJSONTyped(json, false);
}

export function OperatingReportValueModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatingReportValueModel {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['Timestamp'] == null ? undefined : json['Timestamp'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function OperatingReportValueModelToJSON(json: any): OperatingReportValueModel {
    return OperatingReportValueModelToJSONTyped(json, false);
}

export function OperatingReportValueModelToJSONTyped(value?: OperatingReportValueModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Timestamp': value['timestamp'],
        'Value': value['value'],
    };
}

