/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppReportSummaryWater } from './AppReportSummaryWater';
import {
    AppReportSummaryWaterFromJSON,
    AppReportSummaryWaterFromJSONTyped,
    AppReportSummaryWaterToJSON,
    AppReportSummaryWaterToJSONTyped,
} from './AppReportSummaryWater';
import type { AppReportSummaryHeat } from './AppReportSummaryHeat';
import {
    AppReportSummaryHeatFromJSON,
    AppReportSummaryHeatFromJSONTyped,
    AppReportSummaryHeatToJSON,
    AppReportSummaryHeatToJSONTyped,
} from './AppReportSummaryHeat';
import type { AppReportSummaryPower } from './AppReportSummaryPower';
import {
    AppReportSummaryPowerFromJSON,
    AppReportSummaryPowerFromJSONTyped,
    AppReportSummaryPowerToJSON,
    AppReportSummaryPowerToJSONTyped,
} from './AppReportSummaryPower';
import type { AppReportSummaryGas } from './AppReportSummaryGas';
import {
    AppReportSummaryGasFromJSON,
    AppReportSummaryGasFromJSONTyped,
    AppReportSummaryGasToJSON,
    AppReportSummaryGasToJSONTyped,
} from './AppReportSummaryGas';

/**
 * 
 * @export
 * @interface ReportModel
 */
export interface ReportModel {
    /**
     * 
     * @type {string}
     * @memberof ReportModel
     */
    deviceId?: string | null;
    /**
     * 
     * @type {AppReportSummaryPower}
     * @memberof ReportModel
     */
    consumption?: AppReportSummaryPower;
    /**
     * 
     * @type {AppReportSummaryPower}
     * @memberof ReportModel
     */
    ownConsumption?: AppReportSummaryPower;
    /**
     * 
     * @type {AppReportSummaryPower}
     * @memberof ReportModel
     */
    feedIn?: AppReportSummaryPower;
    /**
     * 
     * @type {AppReportSummaryPower}
     * @memberof ReportModel
     */
    generation?: AppReportSummaryPower;
    /**
     * 
     * @type {AppReportSummaryHeat}
     * @memberof ReportModel
     */
    heat?: AppReportSummaryHeat;
    /**
     * 
     * @type {AppReportSummaryGas}
     * @memberof ReportModel
     */
    gas?: AppReportSummaryGas;
    /**
     * 
     * @type {AppReportSummaryWater}
     * @memberof ReportModel
     */
    water?: AppReportSummaryWater;
}

/**
 * Check if a given object implements the ReportModel interface.
 */
export function instanceOfReportModel(value: object): value is ReportModel {
    return true;
}

export function ReportModelFromJSON(json: any): ReportModel {
    return ReportModelFromJSONTyped(json, false);
}

export function ReportModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportModel {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['DeviceId'] == null ? undefined : json['DeviceId'],
        'consumption': json['Consumption'] == null ? undefined : AppReportSummaryPowerFromJSON(json['Consumption']),
        'ownConsumption': json['OwnConsumption'] == null ? undefined : AppReportSummaryPowerFromJSON(json['OwnConsumption']),
        'feedIn': json['FeedIn'] == null ? undefined : AppReportSummaryPowerFromJSON(json['FeedIn']),
        'generation': json['Generation'] == null ? undefined : AppReportSummaryPowerFromJSON(json['Generation']),
        'heat': json['Heat'] == null ? undefined : AppReportSummaryHeatFromJSON(json['Heat']),
        'gas': json['Gas'] == null ? undefined : AppReportSummaryGasFromJSON(json['Gas']),
        'water': json['Water'] == null ? undefined : AppReportSummaryWaterFromJSON(json['Water']),
    };
}

export function ReportModelToJSON(json: any): ReportModel {
    return ReportModelToJSONTyped(json, false);
}

export function ReportModelToJSONTyped(value?: ReportModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'DeviceId': value['deviceId'],
        'Consumption': AppReportSummaryPowerToJSON(value['consumption']),
        'OwnConsumption': AppReportSummaryPowerToJSON(value['ownConsumption']),
        'FeedIn': AppReportSummaryPowerToJSON(value['feedIn']),
        'Generation': AppReportSummaryPowerToJSON(value['generation']),
        'Heat': AppReportSummaryHeatToJSON(value['heat']),
        'Gas': AppReportSummaryGasToJSON(value['gas']),
        'Water': AppReportSummaryWaterToJSON(value['water']),
    };
}

