/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ValuesType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type ValuesType = typeof ValuesType[keyof typeof ValuesType];


export function instanceOfValuesType(value: any): boolean {
    for (const key in ValuesType) {
        if (Object.prototype.hasOwnProperty.call(ValuesType, key)) {
            if (ValuesType[key as keyof typeof ValuesType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ValuesTypeFromJSON(json: any): ValuesType {
    return ValuesTypeFromJSONTyped(json, false);
}

export function ValuesTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValuesType {
    return json as ValuesType;
}

export function ValuesTypeToJSON(value?: ValuesType | null): any {
    return value as any;
}

export function ValuesTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ValuesType {
    return value as ValuesType;
}

