/* tslint:disable */
/* eslint-disable */
/**
 * Kunden API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MyCurrentDataModel,
  MyDeviceModel,
  OperatingReportModel,
  ReportModel,
} from '../models/index';
import {
    MyCurrentDataModelFromJSON,
    MyCurrentDataModelToJSON,
    MyDeviceModelFromJSON,
    MyDeviceModelToJSON,
    OperatingReportModelFromJSON,
    OperatingReportModelToJSON,
    ReportModelFromJSON,
    ReportModelToJSON,
} from '../models/index';

export interface ApiVersionMyIdCurrentGetRequest {
    id: string;
    version: number;
    unit?: string;
}

export interface ApiVersionMyIdDevicesGetRequest {
    id: string;
    version: number;
}

export interface ApiVersionMyIdOperatingGetRequest {
    id: string;
    version: number;
}

export interface ApiVersionMyIdOperatingcsvGetRequest {
    id: string;
    version: number;
}

export interface ApiVersionMyIdReportGetRequest {
    id: string;
    version: number;
    day?: number;
    month?: number;
    year?: number;
    fromhour?: number;
}

export interface ApiVersionMyIdReportcsvGetRequest {
    id: string;
    version: number;
}

/**
 * 
 */
export class MyApi extends runtime.BaseAPI {

    /**
     * Abfrage eines Gerätes durch \"main\" als ID Parameter oder falls mehrere \"MainDevice\" existieren, die poweropti ID als ID parameter verwenden.  <br /><br />  Die Zählerstände liegen in Wh (oder nach Wunsch in kWh siehe unit-Parameter) vor   <br /><br />  Die Leistung liegt in W vor   <br /><br />  Die HT- und NT-Werte werden nur mitgeliefert, wenn Sie einen 2-Tarifzähler haben.   <br /><br />  Zusätzlich gibt bei Strommessung „Outdated“ an ob dieser Wert vom System als veraltet gilt, d.h.wenn der Zeitstempel des Wertes mehr als 60 Sekunden in der Vergangenheit liegt(es gibt allerdings keinerlei Auskunft über den Online-Status des poweroptis, es kann aber auf eine fehlende oder schlechte Verbindung hindeuten) – Das Flag kann für die Integration in Drittsysteme verwendet werden
     * Abfrage der aktuellen Werte für Leistung und Zählerstände eines poweroptis
     */
    async apiVersionMyIdCurrentGetRaw(requestParameters: ApiVersionMyIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MyCurrentDataModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdCurrentGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdCurrentGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/current`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyCurrentDataModelFromJSON(jsonValue));
    }

    /**
     * Abfrage eines Gerätes durch \"main\" als ID Parameter oder falls mehrere \"MainDevice\" existieren, die poweropti ID als ID parameter verwenden.  <br /><br />  Die Zählerstände liegen in Wh (oder nach Wunsch in kWh siehe unit-Parameter) vor   <br /><br />  Die Leistung liegt in W vor   <br /><br />  Die HT- und NT-Werte werden nur mitgeliefert, wenn Sie einen 2-Tarifzähler haben.   <br /><br />  Zusätzlich gibt bei Strommessung „Outdated“ an ob dieser Wert vom System als veraltet gilt, d.h.wenn der Zeitstempel des Wertes mehr als 60 Sekunden in der Vergangenheit liegt(es gibt allerdings keinerlei Auskunft über den Online-Status des poweroptis, es kann aber auf eine fehlende oder schlechte Verbindung hindeuten) – Das Flag kann für die Integration in Drittsysteme verwendet werden
     * Abfrage der aktuellen Werte für Leistung und Zählerstände eines poweroptis
     */
    async apiVersionMyIdCurrentGet(requestParameters: ApiVersionMyIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyCurrentDataModel> {
        const response = await this.apiVersionMyIdCurrentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Abfrage der mit dem Konto verknüpften Geräte    <br />  \"MainDevice\" sind alle Geräte, die Verbrauch bzw. Verbrauch und Einspeisung messen (z.B. Haushaltszähler, zweiter Zähler für Wärmepumpe)   <br />  Zähler zur Messung der Produktion sind keine \"MainDevice\" (z.B. Zähler an PV-Anlage, BHKW)    <br />  „Prosumer“ spiegelt die Einstellung der App wider, ob der poweropti auf einem Zweirichtungszähler montiert ist und somit auch Einspeisung misst(„true“ bei Zweirichtungszähler ansonsten „false“)  <br />  „Division“ entspricht dem Zählertyp, für den der poweropti in der App konfiguriert wurde. Es entspricht folgenden Werten:   <br />   - Kein Typ hinterlegt: -1  <br />   - Stromzähler: 0  <br />   - Kaltwasserzähler: 1  <br />   - Warmwasserzähler: 2  <br />   - Wärmezähler: 3  <br />   - Gaszähler: 4  <br />   - Kalt- und Warmwasserzähler: 5
     * Abfrage der mit dem Konto verknüpften Geräte.
     */
    async apiVersionMyIdDevicesGetRaw(requestParameters: ApiVersionMyIdDevicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MyDeviceModel>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdDevicesGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdDevicesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/devices`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));


        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MyDeviceModelFromJSON));
    }

    /**
     * Abfrage der mit dem Konto verknüpften Geräte    <br />  \"MainDevice\" sind alle Geräte, die Verbrauch bzw. Verbrauch und Einspeisung messen (z.B. Haushaltszähler, zweiter Zähler für Wärmepumpe)   <br />  Zähler zur Messung der Produktion sind keine \"MainDevice\" (z.B. Zähler an PV-Anlage, BHKW)    <br />  „Prosumer“ spiegelt die Einstellung der App wider, ob der poweropti auf einem Zweirichtungszähler montiert ist und somit auch Einspeisung misst(„true“ bei Zweirichtungszähler ansonsten „false“)  <br />  „Division“ entspricht dem Zählertyp, für den der poweropti in der App konfiguriert wurde. Es entspricht folgenden Werten:   <br />   - Kein Typ hinterlegt: -1  <br />   - Stromzähler: 0  <br />   - Kaltwasserzähler: 1  <br />   - Warmwasserzähler: 2  <br />   - Wärmezähler: 3  <br />   - Gaszähler: 4  <br />   - Kalt- und Warmwasserzähler: 5
     * Abfrage der mit dem Konto verknüpften Geräte.
     */
    async apiVersionMyIdDevicesGet(requestParameters: ApiVersionMyIdDevicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MyDeviceModel>> {
        const response = await this.apiVersionMyIdDevicesGetRaw(requestParameters, initOverrides);
        const value = await response.value();
        return value;
    }

    /**
     * Abfrage der historischen Wirkleistung der letzten 60 Minuten ab Abfrage für das \"MainDevice\" (falls mehrere \"MainDevice\" existieren, nächsten Aufruf verwenden), wenn als ID \"main\" verwendet wird.  <br /><br />  Oder Abfrage der historischen Wirkleistung eines Grätes wenn die poweropti ID als ID Parameter verwendet wird.  <br /><br />  Aggregation der Werte auf 2-Minutenbasis - Durchschnittswerte (inklusive Min und Max der Originalwerte).    <br />  Werte liegen in W vor
     * Abruf der Leistungswerte für die letzte Stunde.
     */
    async apiVersionMyIdOperatingGetRaw(requestParameters: ApiVersionMyIdOperatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingReportModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdOperatingGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdOperatingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/operating`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatingReportModelFromJSON(jsonValue));
    }

    /**
     * Abfrage der historischen Wirkleistung der letzten 60 Minuten ab Abfrage für das \"MainDevice\" (falls mehrere \"MainDevice\" existieren, nächsten Aufruf verwenden), wenn als ID \"main\" verwendet wird.  <br /><br />  Oder Abfrage der historischen Wirkleistung eines Grätes wenn die poweropti ID als ID Parameter verwendet wird.  <br /><br />  Aggregation der Werte auf 2-Minutenbasis - Durchschnittswerte (inklusive Min und Max der Originalwerte).    <br />  Werte liegen in W vor
     * Abruf der Leistungswerte für die letzte Stunde.
     */
    async apiVersionMyIdOperatingGet(requestParameters: ApiVersionMyIdOperatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingReportModel> {
        const response = await this.apiVersionMyIdOperatingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Siehe Beschreibung /operating
     * Herunterladen der Leistungswerte als CSV-Datei für die letzten 7 Tage.
     */
    async apiVersionMyIdOperatingcsvGetRaw(requestParameters: ApiVersionMyIdOperatingcsvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdOperatingcsvGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdOperatingcsvGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/operatingcsv`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Siehe Beschreibung /operating
     * Herunterladen der Leistungswerte als CSV-Datei für die letzten 7 Tage.
     */
    async apiVersionMyIdOperatingcsvGet(requestParameters: ApiVersionMyIdOperatingcsvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVersionMyIdOperatingcsvGetRaw(requestParameters, initOverrides);
    }

    /**
     * Abfrage der Deltas eines Gerätes (entweder Verbrauch und Einspeisung oder Generation/Produktion → abhängig davon ob \"MainDevice\"), wenn die poweropti ID als parameter verwendet wird.  <br /><br />  Oder Abfrage aller Geräte, wenn \"all\" als ID verwendet wird.  <br /><br />  Die HT- und NT-Werte werden nur mitgeliefert, wenn Sie einen 2-Tarifzähler haben.   <br />  Folgende Zeitangaben sind möglich:  - Angabe von \"year\": Monatswerte für das angegebene Jahr (liefert die Monatswerte für das angegebene Jahr(XXXX) (vom 1.1. oder vom Aktivierungsstartpunkt bis zum heutigen Tag oder bis zum 31.12.)).  <br />  - Angabe von \"year\" und \"month\": Tageswerte für das angegebene Jahr und den Monat (liefert die Tageswerte für das angegebene Jahr(XXXX) und den Monat(YY) (vom 1. bis zum Letzten des Monats)).  <br />  - Angabe von \"year\", \"month\" und \"day\": Stundenwerte für das angegebene Datum (liefert die Stundenwerte für das konkrete Datum (von 0 Uhr lokaler Zeit bis 23:59 lokaler Zeit)).  <br />  - Angabe von \"year\", \"month\", \"day\" und \"fromHour\": Viertelstundenwerte ab angegebenen Zeitpunkt für 6 Stunden (also 24 Werte,  Z.B. fromHour=6, dann werden Werte von 6:00 bis 11:59 geliefert)  <br />  - Keine Angabe: Letzten 24 Stundenwerte ab Abruf.  <br /><br />  Sollte eine Abfrage nicht die richtige Kombination aus Parametern enthalten z.B. nur Tag und Jahr sind angegeben, tritt der Standardfall ein → letzten 24 Stundenwerte ab Abruf.
     * Abruf der aggregierten Daten.
     */
    async apiVersionMyIdReportGetRaw(requestParameters: ApiVersionMyIdReportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdReportGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdReportGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['day'] != null) {
            queryParameters['day'] = requestParameters['day'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['fromhour'] != null) {
            queryParameters['fromhour'] = requestParameters['fromhour'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/report`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportModelFromJSON(jsonValue));
    }

    /**
     * Abfrage der Deltas eines Gerätes (entweder Verbrauch und Einspeisung oder Generation/Produktion → abhängig davon ob \"MainDevice\"), wenn die poweropti ID als parameter verwendet wird.  <br /><br />  Oder Abfrage aller Geräte, wenn \"all\" als ID verwendet wird.  <br /><br />  Die HT- und NT-Werte werden nur mitgeliefert, wenn Sie einen 2-Tarifzähler haben.   <br />  Folgende Zeitangaben sind möglich:  - Angabe von \"year\": Monatswerte für das angegebene Jahr (liefert die Monatswerte für das angegebene Jahr(XXXX) (vom 1.1. oder vom Aktivierungsstartpunkt bis zum heutigen Tag oder bis zum 31.12.)).  <br />  - Angabe von \"year\" und \"month\": Tageswerte für das angegebene Jahr und den Monat (liefert die Tageswerte für das angegebene Jahr(XXXX) und den Monat(YY) (vom 1. bis zum Letzten des Monats)).  <br />  - Angabe von \"year\", \"month\" und \"day\": Stundenwerte für das angegebene Datum (liefert die Stundenwerte für das konkrete Datum (von 0 Uhr lokaler Zeit bis 23:59 lokaler Zeit)).  <br />  - Angabe von \"year\", \"month\", \"day\" und \"fromHour\": Viertelstundenwerte ab angegebenen Zeitpunkt für 6 Stunden (also 24 Werte,  Z.B. fromHour=6, dann werden Werte von 6:00 bis 11:59 geliefert)  <br />  - Keine Angabe: Letzten 24 Stundenwerte ab Abruf.  <br /><br />  Sollte eine Abfrage nicht die richtige Kombination aus Parametern enthalten z.B. nur Tag und Jahr sind angegeben, tritt der Standardfall ein → letzten 24 Stundenwerte ab Abruf.
     * Abruf der aggregierten Daten.
     */
    async apiVersionMyIdReportGet(requestParameters: ApiVersionMyIdReportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportModel> {
        const response = await this.apiVersionMyIdReportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Siehe Beschreibung /report
     * Herunterladen der Viertelstundenverbrauchswerte als CSV-Datei für die letzten 31 Tage.
     */
    async apiVersionMyIdReportcsvGetRaw(requestParameters: ApiVersionMyIdReportcsvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiVersionMyIdReportcsvGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling apiVersionMyIdReportcsvGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/{version}/my/{id}/reportcsv`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Siehe Beschreibung /report
     * Herunterladen der Viertelstundenverbrauchswerte als CSV-Datei für die letzten 31 Tage.
     */
    async apiVersionMyIdReportcsvGet(requestParameters: ApiVersionMyIdReportcsvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiVersionMyIdReportcsvGetRaw(requestParameters, initOverrides);
    }

}
